### ISSUE TITLE
Custom Field Not Appearing After Installation

### ISSUE THREAD

**Issue by jackadair** [LottieFiles/plugin-strapi#23]
After following installation guide I can see that the plugin is installed here:

![Screenshot 2023-07-11 at 2 32 19 PM](https://github.com/LottieFiles/plugin-strapi/assets/54963231/2ec61a43-5788-4c10-8db0-24dc6d8ae754)

However I am unable to select it as a custom field:

![Screenshot 2023-07-11 at 2 39 10 PM](https://github.com/LottieFiles/plugin-strapi/assets/54963231/928e4456-d3ec-4210-81cc-6c1bc6c17f89)

Just wondering if there was some sort of setup that I missed. Can see this is a pretty inactive plugin but would still appreciate some help as it looks very useful!

Package.json:

```
"dependencies": {
    "@aws-sdk/client-s3": "^3.142.0",
    "@faker-js/faker": "^7.3.0",
    "@shawnvogt/strapi-provider-translate-gct": "^0.0.0-development",
    "@strapi/plugin-i18n": "4.8.0",
    "@strapi/plugin-users-permissions": "4.8.0",
    "@strapi/provider-email-sendgrid": "^4.3.9",
    "@strapi/provider-upload-aws-s3": "^4.3.2",
    "@strapi/strapi": "4.8.0",
    "add": "^2.0.6",
    "onesignal-node": "^3.4.0",
    "strapi-plugin-config-sync": "^1.0.2",
    "strapi-plugin-fuzzy-search": "^1.10.2",
    "strapi-plugin-import-export-entries": "^1.8.0",
    "strapi-plugin-lottie": "0.1.1",
    "strapi-plugin-populate-deep": "^0.1.2",
    "yarn": "^1.22.19"
  },
```

**Comment by hgaharwar** [comment]
Did you get any solution for this ??

**Comment by snilli** [comment]
same issue

**Comment by jackadair** [comment]
@hgaharwar unfortunately no, seems like this plugin is abandoned anyways...

**Comment by aliharis** [comment]
Hello everyone,

Thanks for reporting the issue; we're looking into this issue.
