### ISSUE TITLE
Error when building on docker. Case sensitive

### ISSUE THREAD

**Issue by luxor37** [LottieFiles/plugin-strapi#29]
I am trying to build my strapi build in Docker and I get an error because LottieInputDialogue.tsx is importing Lottie-Loading.json improperly for a Linux environment (using node:18-alpine). 
LottieInputDialogue, line 41: `import LottieLoading from "../Lottie-loading.json";`
Yet the file is named Lottie-Loading.json.
Please let me know when the capitalization is fixed or if you need more details on this issue.
Thanks!

![image](https://github.com/LottieFiles/plugin-strapi/assets/33697235/5385f4c5-574a-4d5b-a3a9-3519eeffcda5)

**Comment by luxor37** [comment]
I can confirm the issue. I simply added a `mv` command before my yarn build in my Dockerfile to rename the Lottie-Loading.json to Lottie-loading.json and it built no problem after. 
Let me know when this is fixed :)

**Comment by naaish-adam** [comment]
We've resolved/addressed the issue in the latest version (0.2.2). Feel free to reopen this issue, or open a new one if you encounter any further issues.
