### ISSUE TITLE
Strapi lotti install problem

### ISSUE THREAD

**Issue by Platformzus** [LottieFiles/plugin-strapi#30]
Can you help us, we are having issues installing and this is what log files say:

Failed to load resource;  the server responded with status 502

1074 uncaught (in input-component.bdbde912.chunk.js:1 (in promise) referenceerror: cannot access ‘as’ before initialization 

23385  uncaught (input-component.bdbde912.chunk.js:1  in promise) referenceerror: cannot access ‘as’ before initialization

**Comment by Platformzus** [comment]
this is a plugin problem. when we enable it it cause issue. but when we remove this then strapi footer working fine

**Comment by naaish-adam** [comment]
Thank you for reporting! We've resolved/addressed the issue in the latest version (0.2.2). Feel free to reopen this issue, or open a new one if you encounter any further issues.
